### ISSUE TITLE
iPad icons not centering

### ISSUE THREAD

**Issue by spaghettiosareyummy** [KeyboardClackers/calc-frontend#2]
When viewing the website on iPad, the two creator icons are not vertically centered. I have set the align-items value to "center" and the issue still exists.

**Comment by spaghettiosareyummy** [comment]
Resolved, only added the  line height to the two text buttons.

**Comment by coldenate** [comment]
yo no tengo un gato

**Comment by spaghettiosareyummy** [comment]
De hecho, tengo un gato señor. Pero tu perro es como un gato

**Comment by spaghettiosareyummy** [comment]
Tu perro somnoliento

**Comment by spaghettiosareyummy** [comment]
Bob Barker quiro jugar CalBalt website. Bob Barker mucho gusta CalBalt websito. Bob Baker necisito el al bano, por favor. Neccesito el al bano, por favor.
